language: php
php:
  - '8.0'
install: composer install --no-interaction
script:
  #    Check coding standards
  - ./vendor/bin/phpcs
  #    Run tests
  - ./vendor/bin/phpunit
branches:
  only: [master]
cache:
  directories:
    - vendor
    - $HOME/.cache/composer